In [ ]:
import numpy as np #tinh toan
import pandas as pd #xu li bang
import seaborn as sns #do thi du lieu
import matplotlib.pyplot as plt # ve
from sklearn.preprocessing import StandardScaler # xu li xu lieu cho dong deu
from sklearn.model_selection import train_test_split # chia du lieu
from keras.layers import Dense,Activation,Dropout,BatchNormalization,LSTM # nhom chuan
from keras.models import Sequential #
from tensorflow.keras.utils import to_categorical #### chỉ cho 1 giá trị (1) hiện lên
from keras import callbacks #
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score,f1_score # đo lường
from tensorflow.keras.optimizers import RMSprop
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import scale
from keras.utils import np_utils
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop
import numpy as np
from tensorflow.keras.optimizers import SGD,Adam
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img, img_to_array
from keras.preprocessing.image import ImageDataGenerator
from skimage import io
import os

In [ ]:
url='/content/drive/MyDrive/Colab Notebooks/FOOD_TOUR_VN'

In [ ]:
generator= ImageDataGenerator(rescale=1./255,validation_split=0.1)
train_data=generator.flow_from_directory(url,target_size=(150,150),batch_size=10,class_mode='categorical',subset='training')
validation_dataset=generator.flow_from_directory(url,target_size=(150,150),batch_size=10,class_mode='categorical',subset='validation')

Found 964 images belonging to 10 classes.
Found 104 images belonging to 10 classes.


In [ ]:
validation_dataset.class_indices

{'BANH_CHUNG': 0,
 'BANH_MI': 1,
 'BANH_XEO': 2,
 'BUN_BO': 3,
 'CANH_CHUA': 4,
 'CAO_LAU': 5,
 'CHAO_LONG': 6,
 'COM_TAM': 7,
 'NEM_CHUA': 8,
 'PHO': 9}

In [ ]:
model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same',input_shape=(100,100,3)))
model.add(Conv2D(32,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))


In [ ]:
model=Sequential()
model.add(Conv2D(64,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(Conv2D(64,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))


In [ ]:
model=Sequential()
model.add(Conv2D(128,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(Conv2D(128,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))


In [ ]:
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dense(10,activation='softmax'))


In [ ]:
opt=SGD(learning_rate=0.002,momentum=0.9)
model.compile (optimizer=opt,loss='categorical_crossentropy', metrics=['accuracy'])
history=model.fit(train_data,epochs=5,batch_size=128,validation_data=validation_dataset,verbose=1)
score=model.evaluate(validation_dataset,verbose=0)
print('Sai số kiểm tra là:',score[0])
print('Độ chính xác kiểm tra là:',score[1])

Epoch 1/5
97/97 [==============================] - 607s 6s/step - loss: 2.8765 - accuracy: 0.1981 - val_loss: 2.1255 - val_accuracy: 0.2115
Epoch 2/5
97/97 [==============================] - 604s 6s/step - loss: 1.7725 - accuracy: 0.3869 - val_loss: 1.9940 - val_accuracy: 0.3846
Epoch 3/5
97/97 [==============================] - 606s 6s/step - loss: 1.0179 - accuracy: 0.6857 - val_loss: 1.8625 - val_accuracy: 0.3846
Epoch 4/5
97/97 [==============================] - 609s 6s/step - loss: 0.3295 - accuracy: 0.9035 - val_loss: 2.3926 - val_accuracy: 0.4038
Epoch 5/5
97/97 [==============================] - 608s 6s/step - loss: 0.0897 - accuracy: 0.9793 - val_loss: 2.8846 - val_accuracy: 0.3365
Sai số kiểm tra là: 2.8845608234405518
Độ chính xác kiểm tra là: 0.3365384638309479


In [ ]:
model.save('/content/drive/MyDrive/Colab Notebooks/MOHINH_H5/FOOD_TOUR_VN.h5')

In [ ]:
img=load_img('banhchung_test.jpg',target_size=(150,150)) #'BANH_CHUNG': 0,'BANH_MI': 1,'BANH_XEO': 2,'BUN_BO': 3,'CANH_CHUA': 4,
#'CAO_LAU': 5,'CHAO_LONG': 6,'COM_TAM': 7,'NEM_CHUA': 8,'PHO': 9
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([0])

In [ ]:
img=load_img('banhmi_test.jpg',target_size=(150,150)) #'BANH_CHUNG': 0,'BANH_MI': 1,'BANH_XEO': 2,'BUN_BO': 3,'CANH_CHUA': 4,
#'CAO_LAU': 5,'CHAO_LONG': 6,'COM_TAM': 7,'NEM_CHUA': 8,'PHO': 9
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([7])

In [ ]:
img=load_img('comtam_test.jpg',target_size=(150,150)) #'BANH_CHUNG': 0,'BANH_MI': 1,'BANH_XEO': 2,'BUN_BO': 3,'CANH_CHUA': 4,
#'CAO_LAU': 5,'CHAO_LONG': 6,'COM_TAM': 7,'NEM_CHUA': 8,'PHO': 9
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([7])