In [ ]:
import numpy as np #tinh toan
import pandas as pd #xu li bang
import seaborn as sns #do thi du lieu
import matplotlib.pyplot as plt # ve
from sklearn.preprocessing import StandardScaler # xu li xu lieu cho dong deu
from sklearn.model_selection import train_test_split # chia du lieu
from keras.layers import Dense,Activation,Dropout,BatchNormalization,LSTM # nhom chuan
from keras.models import Sequential #
from tensorflow.keras.utils import to_categorical #### chỉ cho 1 giá trị (1) hiện lên
from keras import callbacks #
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score,f1_score # đo lường
from tensorflow.keras.optimizers import RMSprop
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import scale
from keras.utils import np_utils
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop
import numpy as np
from tensorflow.keras.optimizers import SGD,Adam
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img, img_to_array
from keras.preprocessing.image import ImageDataGenerator
from skimage import io
import os

In [ ]:
url='/content/drive/MyDrive/Colab Notebooks/FRUIT'

In [ ]:
generator= ImageDataGenerator(rescale=1./255,validation_split=0.1)
train_data=generator.flow_from_directory(url,target_size=(150,150),batch_size=10,class_mode='categorical',subset='training')
validation_dataset=generator.flow_from_directory(url,target_size=(150,150),batch_size=10,class_mode='categorical',subset='validation')

Found 865 images belonging to 10 classes.
Found 90 images belonging to 10 classes.


In [ ]:
validation_dataset.class_indices

{'APPLE': 0,
 'BANANA': 1,
 'CORN': 2,
 'LEMON': 3,
 'LYCHEE': 4,
 'PEACH': 5,
 'RASBERRY': 6,
 'STRAWBERRY': 7,
 'TOMATO': 8,
 'WATERMELON': 9}

In [ ]:
model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same',input_shape=(100,100,3)))
model.add(Conv2D(32,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))

In [ ]:
model=Sequential()
model.add(Conv2D(64,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(Conv2D(64,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))

In [ ]:
model=Sequential()
model.add(Conv2D(128,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(Conv2D(128,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))

In [ ]:
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [ ]:
opt=Adam(lr=0.002)
model.compile (optimizer=opt,loss='categorical_crossentropy', metrics=['accuracy'])
history=model.fit(train_data,epochs=5,batch_size=256,validation_data=validation_dataset,verbose=1)
score=model.evaluate(validation_dataset,verbose=0)
print('Sai số kiểm tra là:',score[0])
print('Độ chính xác kiểm tra là:',score[1])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/5
87/87 [==============================] - 512s 6s/step - loss: 23.7610 - accuracy: 0.7376 - val_loss: 0.9332 - val_accuracy: 0.7667
Epoch 2/5
87/87 [==============================] - 502s 6s/step - loss: 0.2155 - accuracy: 0.9734 - val_loss: 0.4087 - val_accuracy: 0.8889
Epoch 3/5
87/87 [==============================] - 505s 6s/step - loss: 0.0998 - accuracy: 0.9884 - val_loss: 0.4668 - val_accuracy: 0.9111
Epoch 4/5
87/87 [==============================] - 500s 6s/step - loss: 9.4639e-04 - accuracy: 1.0000 - val_loss: 0.6198 - val_accuracy: 0.9111
Epoch 5/5
87/87 [==============================] - 505s 6s/step - loss: 6.1335e-05 - accuracy: 1.0000 - val_loss: 0.6242 - val_accuracy: 0.9111
Sai số kiểm tra là: 0.6242494583129883
Độ chính xác kiểm tra là: 0.9111111164093018


In [ ]:
#'APPLE': 0,'BANANA': 1,'CORN': 2,'LEMON': 3,'LYCHEE': 4,'PEACH': 5,'RASBERRY': 6,'STRAWBERRY': 7,'TOMATO': 8,'WATERMELON': 9
img=load_img('peach_test.jpg',target_size=(150,150)) 
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([5])

In [ ]:
img=load_img('tomato_test.jpg',target_size=(150,150)) 
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([6])

In [ ]:
img=load_img('watermelon_test.jpg',target_size=(150,150)) 
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([9])