In [77]:
import numpy as np #tinh toan
import pandas as pd #xu li bang
import seaborn as sns #do thi du lieu
import matplotlib.pyplot as plt # ve
from sklearn.preprocessing import StandardScaler # xu li xu lieu cho dong deu
from sklearn.model_selection import train_test_split # chia du lieu
from keras.layers import Dense,Activation,Dropout,BatchNormalization,LSTM # nhom chuan
from keras.models import Sequential #
from tensorflow.keras.utils import to_categorical #### chỉ cho 1 giá trị (1) hiện lên
from keras import callbacks #
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score,f1_score # đo lường
from tensorflow.keras.optimizers import RMSprop
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import scale
from keras.utils import np_utils
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop
import numpy as np
from tensorflow.keras.optimizers import SGD,Adam
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img, img_to_array
from keras.preprocessing.image import ImageDataGenerator
from skimage import io
import os

In [ ]:
url='/content/drive/MyDrive/Colab Notebooks/CURRENT_VN'

In [ ]:
generator= ImageDataGenerator(rescale=1./255,validation_split=0.1)
train_data=generator.flow_from_directory(url,target_size=(150,150),batch_size=10,class_mode='categorical',subset='training')
validation_dataset=generator.flow_from_directory(url,target_size=(150,150),batch_size=10,class_mode='categorical',subset='validation')

Found 101 images belonging to 11 classes.
Found 11 images belonging to 11 classes.


In [ ]:
validation_dataset.class_indices

{'100K': 0,
 '10K': 1,
 '1K': 2,
 '200K': 3,
 '200Đ': 4,
 '20K': 5,
 '2K': 6,
 '500K': 7,
 '500Đ': 8,
 '50K': 9,
 '5K': 10}

In [ ]:
model=Sequential()
model.add(Conv2D(32,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same',input_shape=(100,100,3)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(32,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(32,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))

In [ ]:
model=Sequential()
model.add(Conv2D(64,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(Conv2D(64,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))

In [ ]:
model=Sequential()
model.add(Conv2D(128,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(Conv2D(128,(3,3),activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(MaxPooling2D(2,2))

In [ ]:
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(11,activation='softmax'))

In [76]:
opt=Adam(lr=0.002)
model.compile (optimizer=opt,loss='categorical_crossentropy', metrics=['accuracy'])
history=model.fit(train_data,epochs=15,batch_size=128,validation_data=validation_dataset,verbose=1)
score=model.evaluate(validation_dataset,verbose=0)
print('Sai số kiểm tra là:',score[0])
print('Độ chính xác kiểm tra là:',score[1])

Epoch 1/15


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


11/11 [==============================] - 51s 5s/step - loss: 0.1596 - accuracy: 0.9703 - val_loss: 4.5983 - val_accuracy: 0.1818
Epoch 2/15
11/11 [==============================] - 50s 5s/step - loss: 0.4443 - accuracy: 0.9505 - val_loss: 5.0476 - val_accuracy: 0.0909
Epoch 3/15
11/11 [==============================] - 50s 5s/step - loss: 0.6753 - accuracy: 0.8911 - val_loss: 4.2153 - val_accuracy: 0.2727
Epoch 4/15
11/11 [==============================] - 54s 5s/step - loss: 0.7201 - accuracy: 0.9307 - val_loss: 3.1217 - val_accuracy: 0.1818
Epoch 5/15
11/11 [==============================] - 50s 5s/step - loss: 0.6343 - accuracy: 0.8317 - val_loss: 3.6133 - val_accuracy: 0.1818
Epoch 6/15
11/11 [==============================] - 50s 5s/step - loss: 0.5325 - accuracy: 0.8713 - val_loss: 4.4885 - val_accuracy: 0.2727
Epoch 7/15
11/11 [==============================] - 50s 5s/step - loss: 0.1790 - accuracy: 0.9703 - val_loss: 7.2108 - val_accuracy: 0.5455
Epoch 8/15
11/11 [=============

In [78]:
#'100K': 0,'10K': 1,'1K': 2,'200K': 3,'200Đ': 4,'20K': 5,'2K': 6,'500K': 7,'500Đ': 8,'50K': 9,'5K': 10
img=load_img('20k_test.jpg',target_size=(150,150)) 
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([5])

In [79]:
img=load_img('50k_test.jpg',target_size=(150,150)) 
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([7])

In [80]:
img=load_img('100k_test.jpg',target_size=(150,150)) 
img=img_to_array(img)
img=img.reshape(1,150,150,3)
img=img.astype('float32')
img=img/255
np.argmax(model.predict(img),axis=1)

array([0])